import type { Metadata } from "next";
import { Aldrich, Chivo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const aldrich = Aldrich({
  variable: "--font-aldrich",
  subsets: ["latin"],
  weight: "400",
});

const chivo = Chivo({
  variable: "--font-chivo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full relative">
      <body
        className={`${aldrich.variable} ${chivo.variable} antialiased pt-16 pb-32 min-h-full relative h-auto overflow-y-scroll`}
      >
        {children}
        <Navbar />
      </body>
    </html>
  );
}
